### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### GET request to example server
GET http://localhost:3000/api/v1/alumnos

### GET alumno by ID
GET http://localhost:3000/api/v1/alumnos/4

### GET alumno by Nombre
GET http://localhost:3000/api/v1/alumnos?nombre=Bart

### Por nombre Y apellido
GET http://localhost:3000/api/v1/alumnos?nombre=Bart&apellido=Benavente

### GET alumnos by Apellido
GET http://localhost:3000/api/v1/alumnos?apellido=Delgado

### GET alumnoById (que no existe)
GET http://localhost:3000/api/v1/alumnos/9999

### Nuevo alumno
POST http://localhost:3000/api/v1/alumnos
Content-Type: application/json

{
  "nombre": "Ernesto",
  "apellido": "Espinoza",
  "grado": "E lemental"
}
### Delete alumno
DELETE http://localhost:3000/api/v1/alumnos/1