### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA


### GET allAlumnos
GET http://localhost:3000/api/v1/alumnos


### GET alumnoById = 4
GET http://localhost:3000/api/v1/alumnos/4


### GET alumnoByNombre
GET http://localhost:3000/api/v1/alumnos?nombre=Bart


### GET alumnos by Apellido
GET http://localhost:3000/api/v1/alumnos?apellido=Delgado


### GET byNombreYApellido
GET http://localhost:3000/api/v1/alumnos?nombre=Bart&apellido=Benavente


### GET alumnoById (que no existe)
GET http://localhost:3000/api/v1/alumnos/9999


### Nuevo alumno
POST http://localhost:3000/api/v1/alumnos
Content-Type: application/json

{
  "nombre": "ErnErnestoErnestoErnesto",
  "apellido": "Espinoza",
  "grado": "3 lemental"
}


### Nuevo alumno que no cumple validaciones
POST http://localhost:3000/api/v1/alumnos
Content-Type: application/json

{
  "nombre": "ErnErnestoErnestoErnErnestoErnestoErnErnestoErnestoErnesto",
  "apellido": null,
  "grado": "3 lemental"
}

### Put alumno
PUT http://localhost:3000/api/v1/alumnos/1
Content-Type: application/json

{
  "nombre": "Ernesto",
  "apellido": "Espinoza",
    "grado": null
}


### Delete alumno
DELETE http://localhost:3000/api/v1/alumnos/1