/*
-- Borra la tabla si existe
drop table if exists Alumnos;
-- Crea la tabla ALUMNOS
create table ALUMNOS (
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(30) not null,
    apellido varchar(30) not null,
    grado varchar(10) not null,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP not null,
    uuid uuid not null unique
);
*/

insert into asignaturas (nombre)
values ('Programacion'), ( 'Base Datos'), ('Lenguaje de Marcas');

insert into alumnos (nombre, apellido, grado,asignatura_id, uuid)
    values ('Bart', 'Benavente', '1 DAM', '1', UUID());
insert into alumnos (nombre, apellido, grado, asignatura_id, uuid)
    values ('Nicolas', 'Osorio', '2 DAW', '1', UUID());
insert into alumnos (nombre, apellido, grado, asignatura_id, uuid)
    values ('Cesar', 'Campos', '3 DAW','2', UUID());
insert into alumnos (nombre, apellido, grado, asignatura_id, uuid)
    values ('Dani', 'Delgado', '4 ASIR', '3', UUID());

-- Datos para probar paginación
insert into alumnos (nombre, apellido, grado, asignatura_id, uuid)
values ('Laura', 'Bull', '4 ASIR', '3', UUID());
insert into alumnos (nombre, apellido, grado, asignatura_id, uuid)
values ('Jorge', 'Mortis', '3 DAW', '3', UUID());
insert into alumnos (nombre, apellido, grado, asignatura_id, uuid)
values ('Atom', 'Silencer', '2 DAM', '3', UUID());
insert into alumnos (nombre, apellido, grado, asignatura_id, uuid)
values ('Gush', 'Mortred', '3 DAW', '3', UUID());
insert into alumnos (nombre, apellido, grado, asignatura_id, uuid)
values ('Nita', 'Abbadon', '1 DAM', '3', UUID());
insert into alumnos (nombre, apellido, grado, asignatura_id, uuid)
values ('Shelly', 'Juggernaut', '1 ASIR', '3', UUID());
insert into alumnos (nombre, apellido, grado, asignatura_id, uuid)
values ('Darryl', 'Doomsday', '3 DAW', '3', UUID());

-- Datos de ejemplo USUARIOS
-- Contraseña: Admin1
-- No está asociado a ningún titulaar
insert into USUARIOS (nombre, apellidos, username, email, password)
    values ('Admin', 'Apellidadmin', 'admin', 'admin@prueba.net',
        '$2a$10$vPaqZvZkz6jhb7U7k/V/v.5vprfNdOnh4sxi/qpPRkYTzPmFlI9p2');

insert into user_roles (user_id, roles)
    values (1, 'ADMIN');
insert into user_roles (user_id, roles)
    values (1, 'USER');

-- Contraseña: User1
insert into USUARIOS (nombre, apellidos, username, email, password, titular_id)
    values ('User', 'Apelliduser', 'user', 'user#prueba.net',
        '$2a$10$e0MYzXyjpJS7Pd0RVvHwHeFX5cpA8AW8LZyWzUAnmK0jWAbHjg5eW', 2);
insert into user_roles (user_id, roles)
    values (2, 'USER');


-- Contraseña: Test1
insert into USUARIOS (nombre, apellidos, username, email, password)
values ('Test', 'Test Test', 'test', 'test@prueba.net',
        '$2a$10$Pd1yyq2NowcsDf4Cpf/ZXObYFkcycswqHAqBndE1wWJvYwRxlb.Pu');
insert into USER_ROLES (user_id, roles)
values (2, 'USER');