/*
-- Borra la tabla si existe
drop table if exists Alumnos;
-- Crea la tabla ALUMNOS
create table ALUMNOS (
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(30) not null,
    apellido varchar(30) not null,
    grado varchar(10) not null,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP not null,
    uuid uuid not null unique
);
*/

insert into asignaturas (nombre)
        values ('Programacion'), ('Base Datos'), ('Lenguaje Marcas');

insert into alumnos (nombre, apellido, grado, asignatura_id, uuid)
        values ('Nicolas', 'Osorio', '2 DAW', '1', '550e8400-e29b-41d4-a716-446655440000');
insert into alumnos (nombre, apellido, grado,asignatura_id, uuid)
        values ('Bart', 'Benavente', '8 DAM', '1', '550e8400-e29b-41d4-a716-446655440001');
insert into alumnos (nombre, apellido, grado, asignatura_id, uuid)
        values ('Cesar', 'Campos', '3 DAW','2', '550e8400-e29b-41d4-a716-446655440002');
insert into alumnos (nombre, apellido, grado, asignatura_id, uuid)
        values ('Dani', 'Delgado', '4 ASIR', '3', '550e8400-e29b-41d4-a716-446655440003');