### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### getAll
GET http://localhost:3000/api/v1/asignaturas

### getById = 1
GET http://localhost:3000/api/v1/asignaturas/1

### getById = 2
GET http://localhost:3000/api/v1/asignaturas/2

### getById (que no existe)
GET http://localhost:3000/api/v1/asignaturas/9999

### Delete alumno
DELETE http://localhost:3000/api/v1/asignaturas/1

### Paginacion y ordenación
GET http://localhost:3000/api/v1/asignaturas?sortBy=nombre&direction=desc

###
GET  http://localhost:3000/api/v1/asignaturas?sortBy=nombre&direction=desc&size=1

###
GET  http://localhost:3000/api/v1/asignaturas?sortBy=nombre&direction=desc&page=0

