### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA


### GET allAlumnos
GET http://localhost:3000/api/v1/alumnos


### GET alumnoById = 1
GET http://localhost:3000/api/v1/alumnos/1


### GET alumnoByNombre
GET http://localhost:3000/api/v1/alumnos?nombre=Bart


### GET alumnos by Apellido
GET http://localhost:3000/api/v1/alumnos?apellido=Delgado


### GET byNombreYApellido
GET http://localhost:3000/api/v1/alumnos?nombre=Bart&apellido=Benavente


### GET alumnoById (que no existe)
GET http://localhost:3000/api/v1/alumnos/9999


### Nuevo alumno
POST http://localhost:3000/api/v1/alumnos
Content-Type: application/json

{
  "nombre": "Ernesto",
  "apellido": "Espinoza",
  "grado": "3 lemental",
  "asignatura": "Programacion"
}


### Nuevo alumno que no cumple validaciones
POST http://localhost:3000/api/v1/alumnos
Content-Type: application/json

{
  "nombre": "Ernesto",
  "apellido": null,
  "grado": "3 lemental"
}

### Put/Patch alumno
PUT http://localhost:3000/api/v1/alumnos/5
Content-Type: application/json

{
  "nombre": "Ernesto Cambiado",
  "apellido": "Espinoza Cambiado"
}

### Delete alumno
DELETE http://localhost:3000/api/v1/alumnos/1

### Paginacion y ordenacion
GET http://localhost:3000/api/v1/alumnos?sortBy=nombre&direction=desc

###
GET http://localhost:3000/api/v1/alumnos?sortBy=nombre&direction=desc&size=1

###
GET http://localhost:3000/api/v1/alumnos?sortBy=nombre&direction=desc&size=1&page=0
