### Authorization por token, devuleve y guarda un token

### Proceso de Login
POST http://localhost:3000/api/v1/auth/signin
Content-Type: application/json

{
  "username": "admin",
  "password": "Admin1"
}

> {% client.global.set("auth_token", response.body.token); %}

### Proceso de Registro
POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

{
    "nombre": "Test",
    "apellidos": "Test",
    "username": "test2",
    "email": "test@test.com",
    "password": "12345",
    "passwordComprobacion": "12345",
    "roles": ["USER"]
}

### Obtener nuevo token para el usuario registrado
POST http://localhost:3000/api/v1/auth/signin
Content-Type: application/json

{
  "username": "test2",
  "password": "12345"
}

> {% client.global.set("auth_token", response.body.token); %}