DROP TABLE IF EXISTS ALUMNOS CASCADE;

CREATE TABLE ALUMNOS (
                         id bigint generated by default as identity PRIMARY KEY ,
                         nombre varchar(30) not null,
                         apellido varchar(30) not null,
                         grado varchar(10) not null,

                         is_deleted boolean default false,
                         created_at timestamp default current_timestamp not null,
                         updated_at timestamp default current_timestamp ON UPDATE CURRENT_TIMESTAMP not null ,
                         uuid uuid not null unique,
                         asignatura_id bigint

);

