DROP TABLE IF EXISTS ALUMNOS CASCADE;
DROP TABLE IF EXISTS ASIGNATURAS;

CREATE TABLE ALUMNOS (
                         id bigint generated by default as identity PRIMARY KEY ,
                         nombre varchar(30) not null,
                         apellido varchar(30) not null,
                         grado varchar(10) not null,

                         is_deleted boolean default false,
                         created_at timestamp default current_timestamp not null,
                         updated_at timestamp default current_timestamp ON UPDATE CURRENT_TIMESTAMP not null ,
                         uuid uuid not null unique,

                         asignatura_id bigint
);

create table asignaturas(
    id bigint  generated by default as identity PRIMARY KEY,
    nombre varchar(20) not null unique,
    duracionhoras int,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
);